# Estatística descritiva bivariada

A análise bivariada tem como objetivo, estudar as relações (associações para variáveis qualitativas e correlações para variáveis quantitativas) entre duas variáveis. As relações podem ser estudadas por meio da distribuição conjunta de frequências (tabelas de contingência ou de classificação cruzada - *cross-tabulation*), representações gráficas e por meio de medidas-resumo.

## Associação entre duas variáveis qualitativas

### Tabelas de distribuição conjunta de frequências

A forma mais simples de estudar a relação entre duas variáveis qualitativas é por meio de tabelas de distribuição conjunta de frequências, também chamada de tabela de contingência, tabela de classificação cruzada(*cross-tabulation*) ou, ainda, tabela de correspondência. A tabela de contingência é uma tabela de dupla entrada que apresenta as frequências conjuntas das categorias das duas variáveis.

Exemplo: um estudo foi realizado com 200 indivíduos com o intuito de analisar o comportamento conjunto da variável *Operadora de plano de saúde* com a variável *Nível de satisfação*. Verifique se há associação entre as categorias das duas variáveis.

In [1]:
import pandas as pd

DADOS = "../dados/plano_saude.csv"

df_saude = pd.read_csv(DADOS)

df_saude.head()

      operadora satisfacao
0  Total Health      baixo
1  Total Health      baixo
2  Total Health      baixo
3  Total Health      baixo
4  Total Health      baixo

In [2]:
df_saude.tail()

      operadora satisfacao
195  Mena Saúde      medio
196  Mena Saúde       alto
197  Mena Saúde       alto
198  Mena Saúde       alto
199  Mena Saúde       alto

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.crosstab.html